disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - force_cast
  - force_try
  - valid_docs
  - missing_docs
  - identifier_name
  # - colon

opt_in_rules: # some rules are only opt-in
  # - empty_count

included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
large_tuple:
  warning: 5
  error: 7
identifier_name:
  min_length: 1
  max_length: 40

indentation: 2
