platform :ios, '10.0'
use_frameworks!

inhibit_all_warnings!
use_frameworks!

def code_quality
  pod 'SwiftLint'
end

def main_pods
  pod 'SafariCardCollectionViewController', :path => '../'
end

target 'SafariCardCollectionViewController_Example' do
  code_quality
  main_pods
end

target 'SafariCardCollectionViewController_Tests' do
  inherit! :search_paths
end
